In [1]:
import numpy as np
import pandas as pd
from scipy import stats

def calculate_normal_portion(z1=-np.inf, z2=np.inf):
    return stats.norm.cdf(z2) - stats.norm.cdf(z1)

In [2]:
def processor(theme, mu, std, cases):

    df = pd.DataFrame(columns=[f'from', f'to'])

    for case in cases:
        df.loc[len(df)] = case
    df.loc[:, f'z_min'] = (df[f'from'] - mu) / std
    df.loc[:, f'z_max'] = (df[f'to'] - mu) / std

    print('='*100)
    print(f'[{theme}] Dataset')
    display(df)

    print('-'*100)
    print(f'[{theme}] Result')
    for (i_min, i_max, z1, z2) in df.values:
        prob = calculate_normal_portion(z1, z2)
        prob = round(prob, 4)
        print(f'{i_min}~{i_max}\t:\t{prob}')

---
![''](./06_src/06_15_01.png)

In [91]:
theme, n, mu, std = 'Baseball', 162, 245, 40
cases = [[300, np.inf], 
         [-np.inf, 200]]

In [92]:
processor(theme, mu, std, cases)

[Baseball] Dataset


from     to  z_min  z_max
0  300.0    inf  1.375    inf
1   -inf  200.0   -inf -1.125

----------------------------------------------------------------------------------------------------
[Baseball] Result
300.0~inf	:	0.0846
-inf~200.0	:	0.1303


---
![''](./06_src/06_16_01.png)

In [85]:
theme, mu, std = 'IQ', 100, 15
cases = [[140, np.inf], 
         [120, 140], 
         [90, 109]]

In [86]:
processor(theme, mu, std, cases)

[IQ] Dataset


from     to     z_min     z_max
0  140.0    inf  2.666667       inf
1  120.0  140.0  1.333333  2.666667
2   90.0  109.0 -0.666667  0.600000

----------------------------------------------------------------------------------------------------
[IQ] Result
140.0~inf	:	0.0038
120.0~140.0	:	0.0874
90.0~109.0	:	0.4733


---
![''](./06_src/06_17_01.png)

In [83]:
theme, mu, std = 'SAT', 500, 100
cases = [[-np.inf, 400], [650, np.inf]]
cases

[[-inf, 400], [650, inf]]

#### a-b.

In [84]:
processor(theme, mu, std, cases)

[SAT] Dataset


from     to  z_min  z_max
0   -inf  400.0   -inf   -1.0
1  650.0    inf    1.5    inf

----------------------------------------------------------------------------------------------------
[SAT] Result
-inf~400.0	:	0.1587
650.0~inf	:	0.0668


#### c.

In [47]:
stats.norm.ppf(0.8)*std+mu

584.1621233572914

#### d.

In [48]:
stats.norm.ppf(0.6)*std+mu

525.33471031358

---
![''](./06_src/06_18_01.png)

In [79]:
theme, mu, std = 'Smile', 62, 18
cases = np.array([[80, np.inf], [-np.inf, 50]])

print(theme, mu, std)
cases

Smile 62 18


array([[ 80.,  inf],
       [-inf,  50.]])

In [80]:
processor(theme, mu, std, cases)

[Smile] Dataset


from    to  z_min     z_max
0  80.0   inf    1.0       inf
1  -inf  50.0   -inf -0.666667

----------------------------------------------------------------------------------------------------
[Smile] Result
80.0~inf	:	0.1587
-inf~50.0	:	0.2525


---
![''](./06_src/06_19_01.png)

In [74]:
theme, mu, std = 'Electronics', 7.5, 2.5
cases = np.array([[12, np.inf], [5, 10]])

print(theme, mu, std)
cases

Electronics 7.5 2.5


array([[12., inf],
       [ 5., 10.]])

In [77]:
processor(theme, mu, std, cases)

[Electronics] Dataset


from    to  z_min  z_max
0  12.0   inf    1.8    inf
1   5.0  10.0   -1.0    1.0

----------------------------------------------------------------------------------------------------
[Electronics] Result
12.0~inf	:	0.0359
5.0~10.0	:	0.6827


---
![''](./06_src/06_20_01.png)

In [93]:
theme, mu, std = 'Snow', 21.9, 6.5
cases = np.array([[36, np.inf]])

print(theme, mu, std)
cases

Snow 21.9 6.5


array([[36., inf]])

In [94]:
processor(theme, mu, std, cases)

[Snow] Dataset


from   to     z_min  z_max
0  36.0  inf  2.169231    inf

----------------------------------------------------------------------------------------------------
[Snow] Result
36.0~inf	:	0.015


---
![''](./06_src/06_21_01.png)

In [97]:
n = 32

#### a.

In [96]:
prob = 1/4
prob

0.25

#### b.

In [98]:
n * prob

8.0

#### c.

In [107]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Quiz', n * prob, 2.45
cases = np.array([[12.5, np.inf]])

print(theme, mu, std)
cases

Quiz 8.0 2.45


array([[12.5,  inf]])

In [108]:
processor(theme, mu, std, cases)

[Quiz] Dataset


from   to     z_min  z_max
0  12.5  inf  1.836735    inf

----------------------------------------------------------------------------------------------------
[Quiz] Result
12.5~inf	:	0.0331


---
![''](./06_src/06_22_01.png)

In [109]:
n = 20

#### a.

In [110]:
prob = 1/2
n * prob

10.0

#### b.

In [120]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
cases = np.array([[15.5, np.inf], [-np.inf, 7]])

print(theme, mu, std)
cases

Quiz 10.0 2.23606797749979


array([[15.5,  inf],
       [-inf,  7. ]])

In [121]:
processor(theme, mu, std, cases)

[Quiz] Dataset


from   to     z_min     z_max
0  15.5  inf  2.459675       inf
1  -inf  7.0      -inf -1.341641

----------------------------------------------------------------------------------------------------
[Quiz] Result
15.5~inf	:	0.007
-inf~7.0	:	0.0899


---
![''](./06_src/06_23_01.png)

In [122]:
n = 64
prob = 1/2

In [124]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'roulette', n * prob, np.sqrt(n * prob * (1 - prob))
cases = np.array([[39.5, np.inf], [40.5, np.inf]])

print(theme, mu, std)
cases

roulette 32.0 4.0


array([[39.5,  inf],
       [40.5,  inf]])

In [125]:
processor(theme, mu, std, cases)

[roulette] Dataset


from   to  z_min  z_max
0  39.5  inf  1.875    inf
1  40.5  inf  2.125    inf

----------------------------------------------------------------------------------------------------
[roulette] Result
39.5~inf	:	0.0304
40.5~inf	:	0.0168


In [137]:
304-168

136

---
![''](./06_src/06_24_01.png)

#### a.

In [126]:
n = 100
prob = 1/5

In [127]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Card', n * prob, np.sqrt(n * prob * (1 - prob))
cases = np.array([[19.5, np.inf], [20.5, np.inf]])

print(theme, mu, std)
cases

Card 20.0 4.0


array([[19.5,  inf],
       [20.5,  inf]])

In [128]:
processor(theme, mu, std, cases)

[Card] Dataset


from   to  z_min  z_max
0  19.5  inf -0.125    inf
1  20.5  inf  0.125    inf

----------------------------------------------------------------------------------------------------
[Card] Result
19.5~inf	:	0.5497
20.5~inf	:	0.4503


In [139]:
0.5497 - 0.4503

0.09939999999999999

#### b.

In [134]:
n = 36
prob = 1/5

In [135]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Card', n * prob, np.sqrt(n * prob * (1 - prob))
cases = np.array([[9.5, np.inf]])

print(theme, mu, std)
cases

Card 7.2 2.4000000000000004


array([[9.5, inf]])

In [136]:
processor(theme, mu, std, cases)

[Card] Dataset


from   to     z_min  z_max
0   9.5  inf  0.958333    inf

----------------------------------------------------------------------------------------------------
[Card] Result
9.5~inf	:	0.1689


#### c.

In [131]:
n = 64
prob = 1/5

In [132]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Card', n * prob, np.sqrt(n * prob * (1 - prob))
cases = np.array([[15.5, np.inf]])

print(theme, mu, std)
cases

Card 12.8 3.2


array([[15.5,  inf]])

In [133]:
processor(theme, mu, std, cases)

[Card] Dataset


from   to    z_min  z_max
0  15.5  inf  0.84375    inf

----------------------------------------------------------------------------------------------------
[Card] Result
15.5~inf	:	0.1994


---
![''](./06_src/06_25_01.png)

#### a.

In [140]:
n = 84
prob = 0.3

In [144]:
# theme, mu, std = 'Quiz', n * prob, np.sqrt(n * prob * (1 - prob))
# theme, mu, std = 'Card', n * prob, np.sqrt(n * prob * (1 - prob))
theme, mu, std = 'Card', n * prob, 4.2
cases = np.array([[30.5, np.inf], [-np.inf, 20.5]])

print(theme, mu, std)
cases

Card 25.2 4.2


array([[30.5,  inf],
       [-inf, 20.5]])

In [145]:
processor(theme, mu, std, cases)

[Card] Dataset


from    to     z_min     z_max
0  30.5   inf  1.261905       inf
1  -inf  20.5      -inf -1.119048

----------------------------------------------------------------------------------------------------
[Card] Result
30.5~inf	:	0.1035
-inf~20.5	:	0.1316
